name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: ruff-action
        uses: astral-sh/ruff-action@v3.0.1
