name: test
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Checkout Submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1 src/Uncertainpy
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5.2.2
        with: 
          enable-cache: true
          pyproject-file: "pyproject.toml"
      - name: Run tests
        run: uv run --frozen pytest
          
